# Generated by Django 5.0.1 on 2024-05-27 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customdocument", "0002_initial"),
        ("customuser", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="cv",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cv",
                to="customdocument.customdocument",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="passport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="passport",
                to="customdocument.customdocument",
            ),
        ),
    ]
