# Generated by Django 5.0.1 on 2024-05-30 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0002_user_cv_user_passport"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female")],
                default="",
                max_length=10,
                null=True,
            ),
        ),
    ]
