# Generated by Django 5.0.1 on 2024-05-20 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0002_alter_user_managers_user_gender_user_role_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("employer", "employer"), ("employee", "employee")],
                error_messages={"required": "Role must be provided"},
            ),
        ),
    ]
