# Generated by Django 5.0.1 on 2024-05-30 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0003_alter_user_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
