# Generated by Django 5.0.1 on 2024-05-30 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customuser", "0004_remove_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="gender",
        ),
    ]
