# Generated by Django 5.0.1 on 2024-05-29 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customimage", "0002_initial"),
        ("main", "0003_alter_articlepage_content_section_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpage",
            name="feed_image",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="customimage.customimage",
            ),
        ),
    ]
