# Generated by Django 5.0.1 on 2024-05-22 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_landingpage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="LandingPage",
        ),
    ]
