# Generated by Django 5.0.1 on 2024-05-30 09:30

import main.blocks.blocks
import wagtail.blocks
import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0006_alter_articlepage_content_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="content_section",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.TextBlock(
                                        default="Manpower Service from a ISO Certified Recruitment Agency",
                                        label="Hero title",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.TextBlock(
                                        default="The thing we do is take care of your human reosurces",
                                        label="Hero subtitle",
                                        required=False,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Hero image", required=False
                                    ),
                                ),
                                (
                                    "button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    default="Learn More",
                                                    label="Text",
                                                    max_length=100,
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "link",
                                                wagtail.blocks.URLBlock(
                                                    label="Link", required=True
                                                ),
                                            ),
                                            (
                                                "btntype",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("primary", "Primary"),
                                                        ("secondary", "Secondary"),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="CTA",
                                        required=False,
                                    ),
                                ),
                                (
                                    "hash",
                                    main.blocks.blocks.HashBlock(
                                        help_text="Allow navigation to this section within a page. e.g. 'team' allows navigation to /http://your-site.com/#team",
                                        label="Hash",
                                        max_length=80,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
        migrations.AlterField(
            model_name="landingpage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "hero_section",
                        wagtail.blocks.StructBlock(
                            [
                                (
                                    "heading",
                                    wagtail.blocks.TextBlock(
                                        default="Manpower Service from a ISO Certified Recruitment Agency",
                                        label="Hero title",
                                        required=False,
                                    ),
                                ),
                                (
                                    "description",
                                    wagtail.blocks.TextBlock(
                                        default="The thing we do is take care of your human reosurces",
                                        label="Hero subtitle",
                                        required=False,
                                    ),
                                ),
                                (
                                    "image",
                                    wagtail.images.blocks.ImageChooserBlock(
                                        label="Hero image", required=False
                                    ),
                                ),
                                (
                                    "button",
                                    wagtail.blocks.StructBlock(
                                        [
                                            (
                                                "text",
                                                wagtail.blocks.CharBlock(
                                                    default="Learn More",
                                                    label="Text",
                                                    max_length=100,
                                                    required=True,
                                                ),
                                            ),
                                            (
                                                "link",
                                                wagtail.blocks.URLBlock(
                                                    label="Link", required=True
                                                ),
                                            ),
                                            (
                                                "btntype",
                                                wagtail.blocks.ChoiceBlock(
                                                    choices=[
                                                        ("primary", "Primary"),
                                                        ("secondary", "Secondary"),
                                                    ],
                                                    required=False,
                                                ),
                                            ),
                                        ],
                                        label="CTA",
                                        required=False,
                                    ),
                                ),
                                (
                                    "hash",
                                    main.blocks.blocks.HashBlock(
                                        help_text="Allow navigation to this section within a page. e.g. 'team' allows navigation to /http://your-site.com/#team",
                                        label="Hash",
                                        max_length=80,
                                        required=False,
                                    ),
                                ),
                            ]
                        ),
                    )
                ],
                use_json_field=True,
            ),
        ),
    ]
