# Generated by Django 5.0.1 on 2024-05-30 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0007_alter_articlepage_content_section_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="landingpage",
            name="feed_image",
        ),
    ]
