# Generated by Django 5.0.1 on 2024-07-02 05:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0024_alter_articlepage_content_section"),
    ]

    operations = [
        migrations.RenameField(
            model_name="articlepage",
            old_name="content",
            new_name="rich_text",
        ),
    ]
