# Generated by Django 5.0.1 on 2024-07-02 09:24

import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0025_rename_content_articlepage_rich_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="rich_text",
            field=wagtail.fields.RichTextField(
                blank=True, null=True, verbose_name="Rich text"
            ),
        ),
    ]
