# Generated by Django 5.0.1 on 2024-07-04 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0036_alter_articlepage_content_section_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="demopage",
            old_name="content_section",
            new_name="body",
        ),
    ]
