# Generated by Django 5.0.1 on 2024-07-04 18:55

import wagtail.fields
import wagtail.images.blocks
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0040_alter_demopage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="demopage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "my_image_block",
                        wagtail.images.blocks.ImageChooserBlock(
                            help_text="Designed to be used within the main article body content"
                        ),
                    )
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Content Sections",
            ),
        ),
    ]
