# Generated by Django 5.0.1 on 2024-07-08 08:48

import main.blocks.blocks
import wagtail.blocks
import wagtail.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0044_alter_articlepage_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="articlepage",
            name="body",
            field=wagtail.fields.StreamField(
                [
                    (
                        "cover_image",
                        main.blocks.blocks.APIImageChooserBlock(
                            help_text="Pick a cover image for blog",
                            label="Image",
                            required=False,
                        ),
                    ),
                    (
                        "my_paragraph_block",
                        wagtail.blocks.RichTextBlock(
                            help_text="Write content for the article",
                            label="Content",
                            required=False,
                        ),
                    ),
                ],
                blank=True,
                null=True,
                use_json_field=True,
                verbose_name="Article Sections",
            ),
        ),
    ]
