# Generated by Django 5.0.1 on 2024-07-08 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customimage", "0002_initial"),
        ("main", "0045_alter_articlepage_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="articlepage",
            name="cover_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="customimage.customimage",
                verbose_name="Cover Image",
            ),
        ),
    ]
