# Generated by Django 5.0.1 on 2024-06-03 15:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customdocument", "0002_initial"),
        ("jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="job_employment_requirement_agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_employment_requirement_agreement",
                to="customdocument.customdocument",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="job_offer_letter",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_offer_letter",
                to="customdocument.customdocument",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="job_project_agreement",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_project_agreement",
                to="customdocument.customdocument",
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="job_work_permit",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="job_work_permit",
                to="customdocument.customdocument",
            ),
        ),
    ]
