# Generated by Django 5.0.1 on 2024-10-28 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0002_job_job_employment_requirement_agreement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="job",
            name="accommodation",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="experience",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="food_allowance",
            field=models.CharField(
                blank=True,
                choices=[("Yes", "Yes"), ("No", "No")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female"), ("Any", "Any")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="job",
            name="language",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="working_days",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="job",
            name="working_hours",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="job",
            name="salary",
            field=models.CharField(blank=True, default=""),
        ),
    ]
